version: "3"

services:
  portainer:
    networks:
      - service-cluster
    restart: always
    image: portainer/portainer:latest
    container_name: local-portainer
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/:/data

networks:
  service-cluster:
    external:
      name: service-cluster
