version: "3"

services:
  db_postgres:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - service-cluster
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

networks:
  service-cluster:
    external:
      name: service-cluster


volumes:
  postgres:
    external: true
