version: "3"

services:
  local-mongo:
    networks:
      - service-cluster
    restart: always
    image: mongo:latest
    container_name: local-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./data/:/data/db

  mongo-express:
    networks:
      - service-cluster
    links:
      - local-mongo:local-mongo
    depends_on:
      - local-mongo
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: local-mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin

networks:
  service-cluster:
    external:
      name: service-cluster
