version: "3"

services:
  local-redis:
    networks:
      - service-cluster
    restart: always
    image: redis:latest
    container_name: local-redis
    command: redis-server /etc/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./data/:/data
      - ./redis.conf:/etc/redis.conf

networks:
  service-cluster:
    external:
      name: service-cluster
